import type { StrategyDefinition, StrategyTimeframe } from './strategy-framework.types';

export const STRATEGY_TIMEFRAMES: StrategyTimeframe[] = ['1Y', '3Y', '5Y', '10Y', '15Y'];

const commonAssetTypes = ['STOCK'];
const commonRegions = ['IN', 'US', 'EU', 'GLOBAL'];

const rule = (code: string, label: string, input: string, kind: 'REQUIRES' | 'BLOCKS' | 'SCORES' | 'WARNS' = 'REQUIRES', threshold?: number | string | boolean, weight?: number) => ({
  code,
  label,
  input,
  kind,
  threshold,
  weight,
});

export const REGISTERED_STRATEGIES: StrategyDefinition[] = [
  {
    code: 'TREND_MOMENTUM',
    name: 'Trend Momentum',
    description: 'Strong trend continuation where bullish signals align with market, sector, and smart-money context.',
    category: 'ENTRY',
    style: 'MOMENTUM',
    timeframe: 'DAILY_SWING',
    assetTypes: commonAssetTypes,
    supportedRegions: commonRegions,
    version: '1.0.0',
    status: 'ACTIVE',
    requiredInputs: ['latestPrice', 'sma50', 'sma200', 'rawSignal', 'dataQuality', 'marketGate', 'sectorLeadership', 'smartMoneyStatus'],
    entryRules: [
      rule('PRICE_ABOVE_SMA50', 'Price is above SMA50.', 'latestPrice/sma50', 'SCORES', true, 15),
      rule('PRICE_ABOVE_SMA200', 'Price is above SMA200.', 'latestPrice/sma200', 'SCORES', true, 15),
      rule('BULLISH_SIGNAL', 'Raw or calibrated signal is bullish.', 'signal.direction', 'SCORES', 'BULLISH', 20),
      rule('SECTOR_NOT_WEAK', 'Sector is not lagging or weakening.', 'sectorLeadership', 'REQUIRES', true, 10),
      rule('SMART_MONEY_NOT_DISTRIBUTION', 'Smart money is not distribution.', 'smartMoneyStatus', 'REQUIRES', true, 10),
    ],
    exitRules: [rule('PRICE_BELOW_SMA50', 'Review if price closes below SMA50.', 'latestPrice/sma50', 'WARNS')],
    noiseFilters: [
      rule('DATA_NOT_READY', 'Data quality is not ready.', 'dataQuality.signalReadinessStatus', 'BLOCKS', 'NOT_READY'),
      rule('MARKET_CLOSED', 'Market gate is closed.', 'marketGate', 'BLOCKS', 'CLOSED'),
      rule('LOW_RELIABILITY', 'Signal reliability is low or noisy.', 'reliability.status', 'BLOCKS', 'LOW'),
      rule('SMART_MONEY_DISTRIBUTION', 'Smart money distribution contradicts long entry.', 'smartMoneyStatus', 'BLOCKS', 'DISTRIBUTION'),
    ],
    riskRules: [rule('MAX_POSITIONS', 'Use bounded position count in backtests.', 'maxPositions', 'REQUIRES', 10)],
    marketGateRules: [rule('OPEN_OR_SELECTIVE', 'Market gate should be open or selective.', 'marketGate', 'REQUIRES', 'OPEN|SELECTIVE')],
    parameters: { minScore: 75, backtestEntryRule: 'SMA50_ABOVE_SMA200', backtestExitRule: 'PRICE_BELOW_SMA50' },
    explanationTemplate: 'Triggered when bullish trend, signal strength, and context align.',
    examples: {
      triggers: ['Price above SMA50/SMA200 with bullish signal and supportive market gate.'],
      blocks: ['Market gate closed or smart-money distribution is present.'],
    },
  },
  {
    code: 'PULLBACK_IN_UPTREND',
    name: 'Pullback in Uptrend',
    description: 'Long-term uptrend with a controlled pullback near SMA50 and cooled RSI.',
    category: 'ENTRY',
    style: 'PULLBACK',
    timeframe: 'DAILY_SWING',
    assetTypes: commonAssetTypes,
    supportedRegions: commonRegions,
    version: '1.0.0',
    status: 'ACTIVE',
    requiredInputs: ['latestPrice', 'sma50', 'sma200', 'rsi', 'dataQuality', 'marketGate'],
    entryRules: [
      rule('SMA50_ABOVE_SMA200', 'SMA50 is above SMA200.', 'sma50/sma200', 'REQUIRES', true, 25),
      rule('NEAR_SMA50', 'Price is within 5% of SMA50.', 'latestPrice/sma50', 'SCORES', 0.05, 20),
      rule('RSI_COOLED', 'RSI is between 35 and 60.', 'rsi', 'SCORES', '35-60', 15),
    ],
    exitRules: [rule('TREND_BREAK', 'Exit/review if price loses SMA50.', 'latestPrice/sma50', 'WARNS')],
    noiseFilters: [rule('OVEREXTENDED', 'Reject when price is too far above SMA50.', 'latestPrice/sma50', 'BLOCKS', 0.12), rule('MARKET_CLOSED', 'Market gate is closed.', 'marketGate', 'BLOCKS', 'CLOSED')],
    riskRules: [rule('WAIT_FOR_PULLBACK', 'Avoid chasing extended entries.', 'latestPrice/sma50', 'REQUIRES')],
    marketGateRules: [rule('MARKET_HEALTHY', 'Market gate should not be closed.', 'marketGate', 'REQUIRES')],
    parameters: { minScore: 70, nearSmaPercent: 0.05, maxExtensionPercent: 0.12, backtestEntryRule: 'PRICE_ABOVE_SMA50', backtestExitRule: 'PRICE_BELOW_SMA50' },
    explanationTemplate: 'Triggered when an uptrend pulls back into a healthier entry zone.',
    examples: { triggers: ['SMA50>SMA200, price near SMA50, RSI cooled.'], blocks: ['Price is extended far above SMA50.'] },
  },
  {
    code: 'BREAKOUT_CONFIRMATION',
    name: 'Breakout Confirmation',
    description: 'Price near/new high with volume confirmation and reliable bullish context.',
    category: 'ENTRY',
    style: 'BREAKOUT',
    timeframe: 'DAILY_SWING',
    assetTypes: commonAssetTypes,
    supportedRegions: commonRegions,
    version: '1.0.0',
    status: 'ACTIVE',
    requiredInputs: ['latestPrice', 'high52Week', 'volume', 'averageVolume20', 'rawSignal', 'marketGate'],
    entryRules: [rule('NEAR_HIGH', 'Price is within 3% of 52-week high.', 'latestPrice/high52Week', 'SCORES', 0.03, 25), rule('VOLUME_BREAKOUT', 'Volume is at least 1.5x the 20-day average.', 'volume/averageVolume20', 'SCORES', 1.5, 25), rule('BULLISH_SIGNAL', 'Signal direction is bullish.', 'signal.direction', 'REQUIRES', 'BULLISH', 20)],
    exitRules: [rule('FAILED_BREAKOUT', 'Review if price loses SMA50 after breakout.', 'latestPrice/sma50', 'WARNS')],
    noiseFilters: [rule('OVEREXTENDED', 'Reject if price is more than 18% above SMA50.', 'latestPrice/sma50', 'BLOCKS', 0.18), rule('MARKET_CLOSED', 'Market gate is closed.', 'marketGate', 'BLOCKS', 'CLOSED')],
    riskRules: [rule('CONFIRM_VOLUME', 'Volume confirmation is required for stronger breakout rating.', 'averageVolume20', 'REQUIRES')],
    marketGateRules: [rule('SUPPORTIVE_MARKET', 'Market should be open or selective.', 'marketGate', 'REQUIRES')],
    parameters: { minScore: 72, maxExtensionPercent: 0.18, backtestEntryRule: 'SIGNAL_DIRECTION_BULLISH', backtestExitRule: 'PRICE_BELOW_SMA50' },
    explanationTemplate: 'Triggered when breakout price action is confirmed by volume.',
    examples: { triggers: ['New high with high volume and bullish signal.'], blocks: ['Breakout is too extended above SMA50.'] },
  },
  {
    code: 'QUALITY_TREND',
    name: 'Quality Trend',
    description: 'Bullish trend that avoids weak fundamentals and poor data quality.',
    category: 'ENTRY',
    style: 'QUALITY_MOMENTUM',
    timeframe: 'DAILY_SWING',
    assetTypes: commonAssetTypes,
    supportedRegions: commonRegions,
    version: '1.0.0',
    status: 'DRAFT',
    requiredInputs: ['latestPrice', 'sma50', 'sma200', 'fundamentals', 'dataQuality'],
    entryRules: [rule('TREND_UP', 'Price is above SMA50/SMA200.', 'latestPrice/sma', 'SCORES', true, 30), rule('FUNDAMENTALS_AVAILABLE', 'Fundamentals are available and not weak.', 'fundamentals', 'SCORES', true, 20)],
    exitRules: [rule('QUALITY_DETERIORATION', 'Review if fundamental/data quality deteriorates.', 'dataQuality', 'WARNS')],
    noiseFilters: [rule('POOR_DATA_QUALITY', 'Avoid poor coverage/readiness.', 'dataQuality', 'BLOCKS')],
    riskRules: [rule('QUALITY_REQUIRED', 'Requires fundamentals where available.', 'fundamentals', 'REQUIRES')],
    marketGateRules: [rule('MARKET_NOT_CLOSED', 'Market gate should not be closed.', 'marketGate', 'REQUIRES')],
    parameters: { minScore: 68, backtestEntryRule: 'SMA50_ABOVE_SMA200', backtestExitRule: 'PRICE_BELOW_SMA50' },
    explanationTemplate: 'Partial MVP because fundamental quality scoring is still basic.',
    examples: { triggers: ['Trend plus available positive fundamentals.'], blocks: ['Data quality not ready.'] },
  },
  {
    code: 'SMART_MONEY_ACCUMULATION',
    name: 'Smart Money Accumulation',
    description: 'Accumulation confirms a bullish price-volume setup while avoiding distribution.',
    category: 'ENTRY',
    style: 'PRICE_VOLUME',
    timeframe: 'DAILY_SWING',
    assetTypes: commonAssetTypes,
    supportedRegions: commonRegions,
    version: '1.0.0',
    status: 'ACTIVE',
    requiredInputs: ['smartMoneyStatus', 'smartMoneyScore', 'latestPrice', 'volume'],
    entryRules: [rule('ACCUMULATION', 'Smart-money status is accumulation.', 'smartMoneyStatus', 'REQUIRES', 'ACCUMULATION', 35), rule('PRICE_CONFIRMATION', 'Price is above SMA50 or moving higher.', 'latestPrice/sma50', 'SCORES', true, 20)],
    exitRules: [rule('DISTRIBUTION_EXIT', 'Review if smart money turns distribution.', 'smartMoneyStatus', 'WARNS', 'DISTRIBUTION')],
    noiseFilters: [rule('DISTRIBUTION', 'Distribution blocks bullish entry.', 'smartMoneyStatus', 'BLOCKS', 'DISTRIBUTION'), rule('INSUFFICIENT_SMART_MONEY_DATA', 'Smart-money data is insufficient.', 'smartMoneyStatus', 'BLOCKS', 'INSUFFICIENT_DATA')],
    riskRules: [rule('PRICE_VOLUME_ONLY', 'Insider/institutional placeholders are not treated as real proof.', 'smartMoneyDataStatus', 'WARNS')],
    marketGateRules: [rule('MARKET_NOT_CLOSED', 'Market gate should not be closed.', 'marketGate', 'REQUIRES')],
    parameters: { minScore: 70, backtestEntryRule: 'SIGNAL_DIRECTION_BULLISH', backtestExitRule: 'SIGNAL_DIRECTION_BEARISH' },
    explanationTemplate: 'Triggered when local price-volume accumulation supports a bullish setup.',
    examples: { triggers: ['Accumulation with price confirmation.'], blocks: ['Distribution or insufficient price-volume data.'] },
  },
  {
    code: 'SECTOR_LEADER_MOMENTUM',
    name: 'Sector Leader Momentum',
    description: 'Bullish stock signal in a leading or improving sector.',
    category: 'ENTRY',
    style: 'RELATIVE_STRENGTH',
    timeframe: 'DAILY_SWING',
    assetTypes: commonAssetTypes,
    supportedRegions: commonRegions,
    version: '1.0.0',
    status: 'ACTIVE',
    requiredInputs: ['rawSignal', 'sectorLeadership', 'sectorRelativeStrengthScore'],
    entryRules: [rule('BULLISH_SIGNAL', 'Stock signal is bullish.', 'signal.direction', 'REQUIRES', 'BULLISH', 25), rule('SECTOR_LEADING', 'Sector is leading or improving.', 'sectorLeadership', 'SCORES', 'LEADING|IMPROVING', 30)],
    exitRules: [rule('SECTOR_WEAKENING', 'Review if sector weakens.', 'sectorLeadership', 'WARNS', 'WEAKENING')],
    noiseFilters: [rule('SECTOR_LAGGING', 'Lagging sector blocks entry.', 'sectorLeadership', 'BLOCKS', 'LAGGING')],
    riskRules: [rule('RELATIVE_STRENGTH_REQUIRED', 'Requires sector context.', 'sectorLeadership', 'REQUIRES')],
    marketGateRules: [rule('MARKET_NOT_CLOSED', 'Market gate should not be closed.', 'marketGate', 'REQUIRES')],
    parameters: { minScore: 70, backtestEntryRule: 'SMA50_ABOVE_SMA200', backtestExitRule: 'PRICE_BELOW_SMA50' },
    explanationTemplate: 'Triggered when stock momentum aligns with sector leadership.',
    examples: { triggers: ['Bullish stock inside leading sector.'], blocks: ['Sector lagging.'] },
  },
  {
    code: 'DEFENSIVE_EXIT',
    name: 'Defensive Exit Review',
    description: 'Identifies holdings that should be reviewed for exit or risk reduction.',
    category: 'EXIT',
    style: 'DEFENSIVE',
    timeframe: 'DAILY_SWING',
    assetTypes: commonAssetTypes,
    supportedRegions: commonRegions,
    version: '1.0.0',
    status: 'ACTIVE',
    requiredInputs: ['rawSignal', 'latestPrice', 'sma50', 'marketGate'],
    entryRules: [],
    exitRules: [rule('BEARISH_SIGNAL', 'Bearish signal is present.', 'signal.direction', 'SCORES', 'BEARISH', 30), rule('PRICE_BELOW_SMA50', 'Price is below SMA50.', 'latestPrice/sma50', 'SCORES', true, 25), rule('MARKET_WEAK', 'Market gate is closed/selective.', 'marketGate', 'SCORES', 'CLOSED|SELECTIVE', 20)],
    noiseFilters: [rule('NO_HOLDING_CONTEXT', 'Holding context is missing for portfolio-specific action.', 'holding', 'WARNS')],
    riskRules: [rule('REVIEW_ONLY', 'Outputs consider review, never direct financial advice.', 'language', 'REQUIRES')],
    marketGateRules: [rule('WEAK_MARKET_ADDS_RISK', 'Weak market increases review score.', 'marketGate', 'SCORES')],
    parameters: { minScore: 60, backtestEntryRule: 'SIGNAL_DIRECTION_BEARISH', backtestExitRule: 'FIXED_HOLDING_PERIOD' },
    explanationTemplate: 'Triggered when bearish signal and trend breakdown raise holding risk.',
    examples: { triggers: ['Bearish signal plus price below SMA50.'], blocks: ['Insufficient holding/price context lowers confidence.'] },
  },
  {
    code: 'RISK_OFF_AVOIDANCE',
    name: 'Risk-Off Avoidance',
    description: 'Global gate that blocks new long entries in poor market conditions.',
    category: 'GATE',
    style: 'MARKET_GATE',
    timeframe: 'DAILY',
    assetTypes: commonAssetTypes,
    supportedRegions: commonRegions,
    version: '1.0.0',
    status: 'ACTIVE',
    requiredInputs: ['marketGate', 'marketRegime'],
    entryRules: [],
    exitRules: [],
    noiseFilters: [rule('MARKET_CLOSED', 'Market gate closed blocks new long entries.', 'marketGate', 'BLOCKS', 'CLOSED'), rule('RISK_OFF_REGIME', 'Risk-off regime blocks new long entries.', 'marketRegime', 'BLOCKS', 'RISK_OFF')],
    riskRules: [rule('MANAGE_EXISTING_ONLY', 'Manage existing positions only.', 'allowedActions', 'REQUIRES')],
    marketGateRules: [rule('GLOBAL_GATE', 'Applies before long-entry strategies.', 'marketGate', 'REQUIRES')],
    parameters: { minScore: 1, backtestEntryRule: 'SIGNAL_DIRECTION_BULLISH', backtestExitRule: 'SIGNAL_DIRECTION_BEARISH' },
    explanationTemplate: 'Blocks entries when market conditions are not supportive.',
    examples: { triggers: ['Closed market gate returns AVOID.'], blocks: ['This is itself a blocking gate, not a trade entry.'] },
  },
  {
    code: 'MEAN_REVERSION_PULLBACK',
    name: 'Mean Reversion Pullback',
    description: 'Draft strategy for oversold recovery only inside non-broken trend context.',
    category: 'ENTRY',
    style: 'MEAN_REVERSION',
    timeframe: 'DAILY_SWING',
    assetTypes: commonAssetTypes,
    supportedRegions: commonRegions,
    version: '1.0.0',
    status: 'DRAFT',
    requiredInputs: ['rsi', 'sma200', 'latestPrice', 'marketGate'],
    entryRules: [rule('RSI_RECOVERY', 'RSI is recovering from oversold.', 'rsi', 'SCORES', '30-45', 25), rule('NOT_BROKEN_TREND', 'Price remains above SMA200.', 'latestPrice/sma200', 'REQUIRES', true, 20)],
    exitRules: [rule('MEAN_REVERSION_COMPLETE', 'Review when RSI normalizes or trend fails.', 'rsi', 'WARNS')],
    noiseFilters: [rule('FALLING_KNIFE', 'Avoid if price is below SMA200 or market gate is closed.', 'latestPrice/sma200', 'BLOCKS')],
    riskRules: [rule('DRAFT_ONLY', 'Draft until falling-knife handling is proven.', 'status', 'WARNS')],
    marketGateRules: [rule('MARKET_NOT_CLOSED', 'Market gate should not be closed.', 'marketGate', 'REQUIRES')],
    parameters: { minScore: 70, backtestEntryRule: 'PRICE_ABOVE_SMA50', backtestExitRule: 'FIXED_HOLDING_PERIOD' },
    explanationTemplate: 'Draft only; avoids confused falling-knife setups.',
    examples: { triggers: ['RSI recovery while long-term trend remains intact.'], blocks: ['Below SMA200 or closed market gate.'] },
  },
  {
    code: 'LOW_QUALITY_DATA_REJECTION',
    name: 'Low Quality Data Rejection',
    description: 'Reusable filter that excludes poor-quality, unusable, or illiquid instruments.',
    category: 'FILTER',
    style: 'DATA_QUALITY',
    timeframe: 'DAILY',
    assetTypes: commonAssetTypes,
    supportedRegions: commonRegions,
    version: '1.0.0',
    status: 'ACTIVE',
    requiredInputs: ['dataQuality'],
    entryRules: [],
    exitRules: [],
    noiseFilters: [rule('COVERAGE_UNUSABLE', 'Coverage is unusable.', 'dataQuality.coverageStatus', 'BLOCKS', 'UNUSABLE'), rule('READINESS_NOT_READY', 'Signal readiness is not ready.', 'dataQuality.signalReadinessStatus', 'BLOCKS', 'NOT_READY'), rule('ILLIQUID', 'Liquidity is illiquid.', 'dataQuality.liquidityStatus', 'BLOCKS', 'ILLIQUID')],
    riskRules: [rule('LOCAL_FIRST_DATA_CHECK', 'Uses local data quality evaluation only.', 'dataQuality', 'REQUIRES')],
    marketGateRules: [],
    parameters: { minScore: 1, backtestEntryRule: 'SIGNAL_DIRECTION_BULLISH', backtestExitRule: 'SIGNAL_DIRECTION_BEARISH' },
    explanationTemplate: 'Blocks downstream strategies when local data is not trustworthy.',
    examples: { triggers: ['Ready and liquid instruments pass.'], blocks: ['NOT_READY, UNUSABLE, or ILLIQUID.'] },
  },
];

export class StrategyFrameworkRegistry {
  list(): StrategyDefinition[] {
    return REGISTERED_STRATEGIES;
  }

  get(code: string): StrategyDefinition | null {
    return REGISTERED_STRATEGIES.find((strategy) => strategy.code === code.toUpperCase()) ?? null;
  }

  active(): StrategyDefinition[] {
    return REGISTERED_STRATEGIES.filter((strategy) => strategy.status === 'ACTIVE');
  }
}
