// Barrel: this module's type surface is split across cohesive sibling files.
// Every symbol below was previously declared in this file directly; it is now
// re-exported here byte-compatibly so existing imports keep working.

export type {
  HistoricalPrice,
  MarketDataStatus,
  UniverseState,
  UniverseTrustStatus,
  TrustedReviewUniverseStatus,
  TrustedReviewUniverseMode,
  TrustedBaselineRequiredHistoryStatus,
  TrustedBaselineListingDateStatus,
  TrustedBaselineProviderFallbackState,
  TrustedBaselineResidualState,
  ReviewReadinessUserDecision,
  ReviewReadinessBlockerCategory,
  ReviewReadinessBlockerSeverity,
  CatalogSource,
  ProviderSupportStatus,
  ProviderValidationClassification,
  InstrumentSegmentClass,
  MarketDataRepairType,
  MarketDataProviderBusinessRepairStatus,
  MarketDataRepairStateStatus,
  RegionInfo,
  PaginationOptions,
  ValidationResult,
} from './types/market-data-foundation.types.core';

export type {
  SyncSummary,
  MarketDataSyncScopeType,
  MarketDataSyncStateStatus,
  MarketDataSyncSkipReason,
  MarketDataSchedulerReasonCode,
  MarketDataSchedulerDecision,
  LatestStoredCandleInfo,
  MarketDataSyncStateDto,
  ScheduledRegionSyncSummary,
  DailyRefreshEligibilityResult,
  MarketDataSchedulerRegionStatus,
  MarketDataSchedulerStatus,
} from './types/market-data-foundation.types.sync';

export type {
  MarketMoverRange,
  MarketMoverRow,
  MarketMoverRangeSummary,
  MarketMoversSummary,
  MarketMapTile,
  MarketMapGroup,
  MarketMapSummary,
  MarketScanRow52w,
  MarketScanSummary52w,
  MarketScanRowDeliverySpike,
  MarketScanSummaryDeliverySpike,
  MarketScanRowVolumeSpike,
  MarketScanSummaryVolumeSpike,
  MarketScanRowPotentialMovers,
  MarketScanSummaryPotentialMovers,
  OfficialEodBulkSyncEvidence,
} from './types/market-data-foundation.types.scans';

export type {
  SearchResult,
  ProviderValidationResult,
  CompanyMasterData,
  CreateStockRequest,
  V1CreateInstrumentRequest,
  V1Instrument,
  InstrumentUniverseReadiness,
  UpdateStockRequest,
  StockSyncTask,
  WorkerResult,
} from './types/market-data-foundation.types.instrument';

export type {
  UniverseStateCounts,
  UniverseReadinessBlockerSummary,
  MarketDataUniverseSignoff,
  MarketDataUniverseHealth,
  StockMissingDataIssueKind,
  StockMissingDataSample,
  StockColumnMissingDataDiagnostic,
  StockExpectedNullColumnDiagnostic,
  StockIdentityMismatchDiagnostic,
  StockMissingDataDiagnosticsCountMap,
  StockMissingDataDiagnosticsActionCounts,
  StockIdentityMismatchWarning,
  StockMissingDataDiagnostics,
  MarketDataPriceIdentityRepairAction,
  MarketDataPriceIdentityRepairCandidate,
  MarketDataPriceIdentityRepairSummary,
  TrustedReviewUniverseExcludedCounts,
  TrustedReviewUniverseContextGapCounts,
  TrustedReviewUniverseScanPolicy,
  TrustedReviewUniverseHealth,
  ReviewReadinessBlocker,
  ReviewReadinessNextAction,
  ReviewReadinessSummary,
  TrustedReviewUniversePriceRow,
  TrustedReviewUniverseInstrument,
} from './types/market-data-foundation.types.universe';

export type {
  MarketDataRepairRequest,
  ProviderValidationQueue,
  MarketDataRepairRunAction,
  MarketDataRepairRunStatus,
  MarketDataRepairLaneCode,
  MarketDataRepairLane,
  TrustedUniverseRepairWorkbench,
  MarketDataRepairRunRequest,
  MarketDataRepairSourceIdentity,
  MarketDataRepairPlan,
  MarketDataManualMetadataTemplateRow,
  MarketDataManualMetadataTemplate,
  MarketDataRepairSummary,
  MarketDataRepairRunActionResult,
  MarketDataRepairRunResponse,
  MarketDataRepairRunRecord,
} from './types/market-data-foundation.types.repair';

export type {
  CatalogImportRequest,
  CatalogImportSummary,
  CatalogBackfillRequest,
  CatalogBackfillSummary,
  CatalogSyncRunStatus,
  CatalogSyncRunRequest,
  CatalogSyncRunError,
  CatalogSyncRunStatusResponse,
  PriceBackfillRunError,
  PriceBackfillRunRequest,
  PriceBackfillRunStatusResponse,
} from './types/market-data-foundation.types.catalog';

export type {
  V1IngestionRequest,
  V1SyncResult,
  CoreFundamentals,
  CorporateActionType,
  CorporateAction,
  FxRateInput,
} from './types/market-data-foundation.types.ingestion';
