/**
 * EU eurozone equity catalog (FREE, no provider).
 *
 * v1 universe-discovery source for region='EU': a curated set of 297 EUR-denominated
 * large/mid-cap constituents across the eurozone exchanges (XETRA, Euronext
 * Paris/Amsterdam/Brussels/Lisbon/Dublin, Borsa Italiana, BME, Vienna,
 * Helsinki).  Symbols carry the Yahoo suffix (e.g. SAP.DE) so they pass through
 * `toYahooSymbol` unchanged and never collide with US base tickers.
 *
 * Every entry here was live-validated against the keyless Yahoo chart API
 * (exists + has data + meta.currency === 'EUR') before inclusion.  Non-eurozone
 * venues (LSE/GBP, SIX/CHF, Nordics) are intentionally excluded so region='EU'
 * stays single-currency (EUR), matching the EU market profile.
 *
 * This is the EU analogue of `us-catalog-source` (NASDAQ Trader files); EU has
 * no free NASDAQ-Trader-style directory, so the universe is curated rather than
 * fetched.  The ingestion service owns all DB writes.
 */

export interface EuUniverseCandidate {
  /** Canonical, Yahoo-suffixed symbol (e.g. 'SAP.DE'). */
  symbol: string;
  name: string;
  /** App exchange code (XETRA, EURONEXT_PAR, BORSA_ITALIANA, BME, ...). */
  exchange: string;
  /** ISO-3166 alpha-2 country of the primary listing. */
  country: string;
}

export const EU_EUROZONE_UNIVERSE: EuUniverseCandidate[] = [
  { symbol: 'A2A.MI', name: 'A2A SpA', exchange: 'BORSA_ITALIANA', country: 'IT' },
  { symbol: 'A5G.IR', name: 'AIB Group plc', exchange: 'EURONEXT_DUB', country: 'IE' },
  { symbol: 'AALB.AS', name: 'Aalberts NV', exchange: 'EURONEXT_AMS', country: 'NL' },
  { symbol: 'ABI.BR', name: 'Anheuser-Busch InBev SA', exchange: 'EURONEXT_BRU', country: 'BE' },
  { symbol: 'AC.PA', name: 'Accor SA', exchange: 'EURONEXT_PAR', country: 'FR' },
  { symbol: 'ACA.PA', name: 'Credit Agricole SA', exchange: 'EURONEXT_PAR', country: 'FR' },
  { symbol: 'ACKB.BR', name: 'Ackermans & van Haaren NV', exchange: 'EURONEXT_BRU', country: 'BE' },
  { symbol: 'ACS.MC', name: 'ACS Actividades de Construccion y Servicios SA', exchange: 'BME', country: 'ES' },
  { symbol: 'ACX.MC', name: 'Acerinox SA', exchange: 'BME', country: 'ES' },
  { symbol: 'AD.AS', name: 'Koninklijke Ahold Delhaize NV', exchange: 'EURONEXT_AMS', country: 'NL' },
  { symbol: 'ADS.DE', name: 'adidas AG', exchange: 'XETRA', country: 'DE' },
  { symbol: 'ADYEN.AS', name: 'Adyen NV', exchange: 'EURONEXT_AMS', country: 'NL' },
  { symbol: 'AED.BR', name: 'Aedifica SA', exchange: 'EURONEXT_BRU', country: 'BE' },
  { symbol: 'AENA.MC', name: 'Aena SME SA', exchange: 'BME', country: 'ES' },
  { symbol: 'AFX.DE', name: 'Carl Zeiss Meditec AG', exchange: 'XETRA', country: 'DE' },
  { symbol: 'AGN.AS', name: 'Aegon Ltd', exchange: 'EURONEXT_AMS', country: 'NL' },
  { symbol: 'AGS.BR', name: 'ageas SA', exchange: 'EURONEXT_BRU', country: 'BE' },
  { symbol: 'AI.PA', name: 'Air Liquide SA', exchange: 'EURONEXT_PAR', country: 'FR' },
  { symbol: 'AIR.DE', name: 'Airbus SE', exchange: 'XETRA', country: 'DE' },
  { symbol: 'AIR.PA', name: 'Airbus SE', exchange: 'EURONEXT_PAR', country: 'FR' },
  { symbol: 'AKE.PA', name: 'Arkema SA', exchange: 'EURONEXT_PAR', country: 'FR' },
  { symbol: 'AKZA.AS', name: 'Akzo Nobel NV', exchange: 'EURONEXT_AMS', country: 'NL' },
  { symbol: 'ALO.PA', name: 'Alstom SA', exchange: 'EURONEXT_PAR', country: 'FR' },
  { symbol: 'ALV.DE', name: 'Allianz SE', exchange: 'XETRA', country: 'DE' },
  { symbol: 'AMP.MI', name: 'Amplifon SpA', exchange: 'BORSA_ITALIANA', country: 'IT' },
  { symbol: 'AMS.MC', name: 'Amadeus IT Group SA', exchange: 'BME', country: 'ES' },
  { symbol: 'AMUN.PA', name: 'Amundi SA', exchange: 'EURONEXT_PAR', country: 'FR' },
  { symbol: 'ANA.MC', name: 'Acciona SA', exchange: 'BME', country: 'ES' },
  { symbol: 'ANDR.VI', name: 'Andritz AG', exchange: 'VIENNA', country: 'AT' },
  { symbol: 'ANE.MC', name: 'Corporacion Acciona Energias Renovables SA', exchange: 'BME', country: 'ES' },
  { symbol: 'ARCAD.AS', name: 'Arcadis NV', exchange: 'EURONEXT_AMS', country: 'NL' },
  { symbol: 'ASM.AS', name: 'ASM International NV', exchange: 'EURONEXT_AMS', country: 'NL' },
  { symbol: 'ASML.AS', name: 'ASML Holding NV', exchange: 'EURONEXT_AMS', country: 'NL' },
  { symbol: 'ASRNL.AS', name: 'ASR Nederland NV', exchange: 'EURONEXT_AMS', country: 'NL' },
  { symbol: 'AT1.DE', name: 'Aroundtown SA', exchange: 'XETRA', country: 'DE' },
  { symbol: 'BAMI.MI', name: 'Banco BPM SpA', exchange: 'BORSA_ITALIANA', country: 'IT' },
  { symbol: 'BAMNB.AS', name: 'Koninklijke BAM Groep NV', exchange: 'EURONEXT_AMS', country: 'NL' },
  { symbol: 'BAR.BR', name: 'Barco NV', exchange: 'EURONEXT_BRU', country: 'BE' },
  { symbol: 'BAS.DE', name: 'BASF SE', exchange: 'XETRA', country: 'DE' },
  { symbol: 'BAYN.DE', name: 'Bayer AG', exchange: 'XETRA', country: 'DE' },
  { symbol: 'BBVA.MC', name: 'Banco Bilbao Vizcaya Argentaria SA', exchange: 'BME', country: 'ES' },
  { symbol: 'BC.MI', name: 'Brunello Cucinelli SpA', exchange: 'BORSA_ITALIANA', country: 'IT' },
  { symbol: 'BCP.LS', name: 'Banco Comercial Portugues SA', exchange: 'EURONEXT_LIS', country: 'PT' },
  { symbol: 'BEI.DE', name: 'Beiersdorf AG', exchange: 'XETRA', country: 'DE' },
  { symbol: 'BEKB.BR', name: 'Bekaert SA', exchange: 'EURONEXT_BRU', country: 'BE' },
  { symbol: 'BESI.AS', name: 'BE Semiconductor Industries NV', exchange: 'EURONEXT_AMS', country: 'NL' },
  { symbol: 'BG.VI', name: 'BAWAG Group AG', exchange: 'VIENNA', country: 'AT' },
  { symbol: 'BIRG.IR', name: 'Bank of Ireland Group plc', exchange: 'EURONEXT_DUB', country: 'IE' },
  { symbol: 'BKT.MC', name: 'Bankinter SA', exchange: 'BME', country: 'ES' },
  { symbol: 'BMED.MI', name: 'Banca Mediolanum SpA', exchange: 'BORSA_ITALIANA', country: 'IT' },
  { symbol: 'BMW.DE', name: 'Bayerische Motoren Werke AG', exchange: 'XETRA', country: 'DE' },
  { symbol: 'BN.PA', name: 'Danone SA', exchange: 'EURONEXT_PAR', country: 'FR' },
  { symbol: 'BNP.PA', name: 'BNP Paribas SA', exchange: 'EURONEXT_PAR', country: 'FR' },
  { symbol: 'BNR.DE', name: 'Brenntag SE', exchange: 'XETRA', country: 'DE' },
  { symbol: 'BOSS.DE', name: 'Hugo Boss AG', exchange: 'XETRA', country: 'DE' },
  { symbol: 'BPE.MI', name: 'BPER Banca SpA', exchange: 'BORSA_ITALIANA', country: 'IT' },
  { symbol: 'BVI.PA', name: 'Bureau Veritas SA', exchange: 'EURONEXT_PAR', country: 'FR' },
  { symbol: 'BZU.MI', name: 'Buzzi SpA', exchange: 'BORSA_ITALIANA', country: 'IT' },
  { symbol: 'CA.PA', name: 'Carrefour SA', exchange: 'EURONEXT_PAR', country: 'FR' },
  { symbol: 'CABK.MC', name: 'CaixaBank SA', exchange: 'BME', country: 'ES' },
  { symbol: 'CAI.VI', name: 'CA Immobilien Anlagen AG', exchange: 'VIENNA', country: 'AT' },
  { symbol: 'CAP.PA', name: 'Capgemini SE', exchange: 'EURONEXT_PAR', country: 'FR' },
  { symbol: 'CBK.DE', name: 'Commerzbank AG', exchange: 'XETRA', country: 'DE' },
  { symbol: 'CLNX.MC', name: 'Cellnex Telecom SA', exchange: 'BME', country: 'ES' },
  { symbol: 'COFA.PA', name: 'Coface SA', exchange: 'EURONEXT_PAR', country: 'FR' },
  { symbol: 'COFB.BR', name: 'Cofinimmo SA', exchange: 'EURONEXT_BRU', country: 'BE' },
  { symbol: 'COK.DE', name: 'Cancom SE', exchange: 'XETRA', country: 'DE' },
  { symbol: 'COL.MC', name: 'Inmobiliaria Colonial SOCIMI SA', exchange: 'BME', country: 'ES' },
  { symbol: 'COLR.BR', name: 'Etablissementen Franz Colruyt NV', exchange: 'EURONEXT_BRU', country: 'BE' },
  { symbol: 'CON.DE', name: 'Continental AG', exchange: 'XETRA', country: 'DE' },
  { symbol: 'COR.LS', name: 'Corticeira Amorim SGPS SA', exchange: 'EURONEXT_LIS', country: 'PT' },
  { symbol: 'CPR.MI', name: 'Davide Campari-Milano NV', exchange: 'BORSA_ITALIANA', country: 'IT' },
  { symbol: 'CRBN.AS', name: 'Corbion NV', exchange: 'EURONEXT_AMS', country: 'NL' },
  { symbol: 'CS.PA', name: 'AXA SA', exchange: 'EURONEXT_PAR', country: 'FR' },
  { symbol: 'CTT.LS', name: 'CTT - Correios de Portugal SA', exchange: 'EURONEXT_LIS', country: 'PT' },
  { symbol: 'DB1.DE', name: 'Deutsche Boerse AG', exchange: 'XETRA', country: 'DE' },
  { symbol: 'DBK.DE', name: 'Deutsche Bank AG', exchange: 'XETRA', country: 'DE' },
  { symbol: 'DG.PA', name: 'Vinci SA', exchange: 'EURONEXT_PAR', country: 'FR' },
  { symbol: 'DHL.DE', name: 'DHL Group', exchange: 'XETRA', country: 'DE' },
  { symbol: 'DIA.MI', name: 'DiaSorin SpA', exchange: 'BORSA_ITALIANA', country: 'IT' },
  { symbol: 'DOC.VI', name: 'DO & CO AG', exchange: 'VIENNA', country: 'AT' },
  { symbol: 'DSFIR.AS', name: 'DSM-Firmenich AG', exchange: 'EURONEXT_AMS', country: 'NL' },
  { symbol: 'DSY.PA', name: 'Dassault Systemes SE', exchange: 'EURONEXT_PAR', country: 'FR' },
  { symbol: 'DTE.DE', name: 'Deutsche Telekom AG', exchange: 'XETRA', country: 'DE' },
  { symbol: 'DUE.DE', name: 'Duerr AG', exchange: 'XETRA', country: 'DE' },
  { symbol: 'EBS.VI', name: 'Erste Group Bank AG', exchange: 'VIENNA', country: 'AT' },
  { symbol: 'EDEN.PA', name: 'Edenred SE', exchange: 'EURONEXT_PAR', country: 'FR' },
  { symbol: 'EDP.LS', name: 'EDP - Energias de Portugal SA', exchange: 'EURONEXT_LIS', country: 'PT' },
  { symbol: 'EDPR.LS', name: 'EDP Renovaveis SA', exchange: 'EURONEXT_LIS', country: 'PT' },
  { symbol: 'EL.PA', name: 'EssilorLuxottica SA', exchange: 'EURONEXT_PAR', country: 'FR' },
  { symbol: 'ELE.MC', name: 'Endesa SA', exchange: 'BME', country: 'ES' },
  { symbol: 'ELI.BR', name: 'Elia Group SA', exchange: 'EURONEXT_BRU', country: 'BE' },
  { symbol: 'ELIS.PA', name: 'Elis SA', exchange: 'EURONEXT_PAR', country: 'FR' },
  { symbol: 'ELISA.HE', name: 'Elisa Oyj', exchange: 'HELSINKI', country: 'FI' },
  { symbol: 'EN.PA', name: 'Bouygues SA', exchange: 'EURONEXT_PAR', country: 'FR' },
  { symbol: 'ENEL.MI', name: 'Enel SpA', exchange: 'BORSA_ITALIANA', country: 'IT' },
  { symbol: 'ENG.MC', name: 'Enagas SA', exchange: 'BME', country: 'ES' },
  { symbol: 'ENGI.PA', name: 'Engie SA', exchange: 'EURONEXT_PAR', country: 'FR' },
  { symbol: 'ENI.MI', name: 'Eni SpA', exchange: 'BORSA_ITALIANA', country: 'IT' },
  { symbol: 'ENR.DE', name: 'Siemens Energy AG', exchange: 'XETRA', country: 'DE' },
  { symbol: 'EOAN.DE', name: 'E.ON SE', exchange: 'XETRA', country: 'DE' },
  { symbol: 'ERF.PA', name: 'Eurofins Scientific SE', exchange: 'EURONEXT_PAR', country: 'FR' },
  { symbol: 'ERG.MI', name: 'ERG SpA', exchange: 'BORSA_ITALIANA', country: 'IT' },
  { symbol: 'EVD.DE', name: 'CTS Eventim AG & Co KGaA', exchange: 'XETRA', country: 'DE' },
  { symbol: 'EVK.DE', name: 'Evonik Industries AG', exchange: 'XETRA', country: 'DE' },
  { symbol: 'FAGR.BR', name: 'Fagron NV', exchange: 'EURONEXT_BRU', country: 'BE' },
  { symbol: 'FBK.MI', name: 'FinecoBank SpA', exchange: 'BORSA_ITALIANA', country: 'IT' },
  { symbol: 'FDR.MC', name: 'Fluidra SA', exchange: 'BME', country: 'ES' },
  { symbol: 'FER.MC', name: 'Ferrovial SE', exchange: 'BME', country: 'ES' },
  { symbol: 'FME.DE', name: 'Fresenius Medical Care AG', exchange: 'XETRA', country: 'DE' },
  { symbol: 'FNTN.DE', name: 'freenet AG', exchange: 'XETRA', country: 'DE' },
  { symbol: 'FORTUM.HE', name: 'Fortum Oyj', exchange: 'HELSINKI', country: 'FI' },
  { symbol: 'FR.PA', name: 'Valeo SE', exchange: 'EURONEXT_PAR', country: 'FR' },
  { symbol: 'FRE.DE', name: 'Fresenius SE & Co KGaA', exchange: 'XETRA', country: 'DE' },
  { symbol: 'FUR.AS', name: 'Fugro NV', exchange: 'EURONEXT_AMS', country: 'NL' },
  { symbol: 'G.MI', name: 'Assicurazioni Generali SpA', exchange: 'BORSA_ITALIANA', country: 'IT' },
  { symbol: 'G24.DE', name: 'Scout24 SE', exchange: 'XETRA', country: 'DE' },
  { symbol: 'GALP.LS', name: 'Galp Energia SGPS SA', exchange: 'EURONEXT_LIS', country: 'PT' },
  { symbol: 'GBLB.BR', name: 'Groupe Bruxelles Lambert SA', exchange: 'EURONEXT_BRU', country: 'BE' },
  { symbol: 'GET.PA', name: 'Getlink SE', exchange: 'EURONEXT_PAR', country: 'FR' },
  { symbol: 'GL9.IR', name: 'Glanbia plc', exchange: 'EURONEXT_DUB', country: 'IE' },
  { symbol: 'GLE.PA', name: 'Societe Generale SA', exchange: 'EURONEXT_PAR', country: 'FR' },
  { symbol: 'GLPG.BR', name: 'Galapagos NV', exchange: 'EURONEXT_BRU', country: 'BE' },
  { symbol: 'GRF.MC', name: 'Grifols SA', exchange: 'BME', country: 'ES' },
  { symbol: 'GVR.IR', name: 'Glanbia plc', exchange: 'EURONEXT_DUB', country: 'IE' },
  { symbol: 'GXI.DE', name: 'Gerresheimer AG', exchange: 'XETRA', country: 'DE' },
  { symbol: 'HEI.DE', name: 'Heidelberg Materials AG', exchange: 'XETRA', country: 'DE' },
  { symbol: 'HEIA.AS', name: 'Heineken NV', exchange: 'EURONEXT_AMS', country: 'NL' },
  { symbol: 'HEIO.AS', name: 'Heineken Holding NV', exchange: 'EURONEXT_AMS', country: 'NL' },
  { symbol: 'HEN3.DE', name: 'Henkel AG & Co KGaA', exchange: 'XETRA', country: 'DE' },
  { symbol: 'HER.MI', name: 'Hera SpA', exchange: 'BORSA_ITALIANA', country: 'IT' },
  { symbol: 'HFG.DE', name: 'HelloFresh SE', exchange: 'XETRA', country: 'DE' },
  { symbol: 'HNR1.DE', name: 'Hannover Rueck SE', exchange: 'XETRA', country: 'DE' },
  { symbol: 'HO.PA', name: 'Thales SA', exchange: 'EURONEXT_PAR', country: 'FR' },
  { symbol: 'HUH1V.HE', name: 'Huhtamaki Oyj', exchange: 'HELSINKI', country: 'FI' },
  { symbol: 'IAG.MC', name: 'International Consolidated Airlines Group SA', exchange: 'BME', country: 'ES' },
  { symbol: 'IBE.MC', name: 'Iberdrola SA', exchange: 'BME', country: 'ES' },
  { symbol: 'IFX.DE', name: 'Infineon Technologies AG', exchange: 'XETRA', country: 'DE' },
  { symbol: 'IG.MI', name: 'Italgas SpA', exchange: 'BORSA_ITALIANA', country: 'IT' },
  { symbol: 'IMCD.AS', name: 'IMCD NV', exchange: 'EURONEXT_AMS', country: 'NL' },
  { symbol: 'INGA.AS', name: 'ING Groep NV', exchange: 'EURONEXT_AMS', country: 'NL' },
  { symbol: 'INW.MI', name: 'Infrastrutture Wireless Italiane SpA', exchange: 'BORSA_ITALIANA', country: 'IT' },
  { symbol: 'IP.MI', name: 'Interpump Group SpA', exchange: 'BORSA_ITALIANA', country: 'IT' },
  { symbol: 'IPR.LS', name: 'Ibersol SGPS SA', exchange: 'EURONEXT_LIS', country: 'PT' },
  { symbol: 'IR5B.IR', name: 'Irish Continental Group plc', exchange: 'EURONEXT_DUB', country: 'IE' },
  { symbol: 'ISP.MI', name: 'Intesa Sanpaolo SpA', exchange: 'BORSA_ITALIANA', country: 'IT' },
  { symbol: 'ITX.MC', name: 'Industria de Diseno Textil SA', exchange: 'BME', country: 'ES' },
  { symbol: 'JMT.LS', name: 'Jeronimo Martins SGPS SA', exchange: 'EURONEXT_LIS', country: 'PT' },
  { symbol: 'JUN3.DE', name: 'Jungheinrich AG', exchange: 'XETRA', country: 'DE' },
  { symbol: 'KBC.BR', name: 'KBC Group NV', exchange: 'EURONEXT_BRU', country: 'BE' },
  { symbol: 'KCO.DE', name: 'Kloeckner & Co SE', exchange: 'XETRA', country: 'DE' },
  { symbol: 'KCR.HE', name: 'Konecranes Oyj', exchange: 'HELSINKI', country: 'FI' },
  { symbol: 'KER.PA', name: 'Kering SA', exchange: 'EURONEXT_PAR', country: 'FR' },
  { symbol: 'KESKOB.HE', name: 'Kesko Oyj', exchange: 'HELSINKI', country: 'FI' },
  { symbol: 'KGX.DE', name: 'KION Group AG', exchange: 'XETRA', country: 'DE' },
  { symbol: 'KNEBV.HE', name: 'KONE Oyj', exchange: 'HELSINKI', country: 'FI' },
  { symbol: 'KPN.AS', name: 'Koninklijke KPN NV', exchange: 'EURONEXT_AMS', country: 'NL' },
  { symbol: 'KRN.DE', name: 'Krones AG', exchange: 'XETRA', country: 'DE' },
  { symbol: 'KRX.IR', name: 'Kingspan Group plc', exchange: 'EURONEXT_DUB', country: 'IE' },
  { symbol: 'KRZ.IR', name: 'Kerry Group plc', exchange: 'EURONEXT_DUB', country: 'IE' },
  { symbol: 'LDO.MI', name: 'Leonardo SpA', exchange: 'BORSA_ITALIANA', country: 'IT' },
  { symbol: 'LEG.DE', name: 'LEG Immobilien SE', exchange: 'XETRA', country: 'DE' },
  { symbol: 'LHA.DE', name: 'Deutsche Lufthansa AG', exchange: 'XETRA', country: 'DE' },
  { symbol: 'LIGHT.AS', name: 'Signify NV', exchange: 'EURONEXT_AMS', country: 'NL' },
  { symbol: 'LIN.DE', name: 'Linde plc', exchange: 'XETRA', country: 'DE' },
  { symbol: 'LNZ.VI', name: 'Lenzing AG', exchange: 'VIENNA', country: 'AT' },
  { symbol: 'LOG.MC', name: 'Logista Integral SA', exchange: 'BME', country: 'ES' },
  { symbol: 'LR.PA', name: 'Legrand SA', exchange: 'EURONEXT_PAR', country: 'FR' },
  { symbol: 'LXS.DE', name: 'Lanxess AG', exchange: 'XETRA', country: 'DE' },
  { symbol: 'MAP.MC', name: 'Mapfre SA', exchange: 'BME', country: 'ES' },
  { symbol: 'MB.MI', name: 'Mediobanca SpA', exchange: 'BORSA_ITALIANA', country: 'IT' },
  { symbol: 'MBG.DE', name: 'Mercedes-Benz Group AG', exchange: 'XETRA', country: 'DE' },
  { symbol: 'MC.PA', name: 'LVMH Moet Hennessy Louis Vuitton', exchange: 'EURONEXT_PAR', country: 'FR' },
  { symbol: 'MELE.BR', name: 'Melexis NV', exchange: 'EURONEXT_BRU', country: 'BE' },
  { symbol: 'MERY.PA', name: 'Mersen SA', exchange: 'EURONEXT_PAR', country: 'FR' },
  { symbol: 'METSO.HE', name: 'Metso Oyj', exchange: 'HELSINKI', country: 'FI' },
  { symbol: 'ML.PA', name: 'Michelin SCA', exchange: 'EURONEXT_PAR', country: 'FR' },
  { symbol: 'MMK.VI', name: 'Mayr-Melnhof Karton AG', exchange: 'VIENNA', country: 'AT' },
  { symbol: 'MONC.MI', name: 'Moncler SpA', exchange: 'BORSA_ITALIANA', country: 'IT' },
  { symbol: 'MRK.DE', name: 'Merck KGaA', exchange: 'XETRA', country: 'DE' },
  { symbol: 'MRL.MC', name: 'Merlin Properties SOCIMI SA', exchange: 'BME', country: 'ES' },
  { symbol: 'MUV2.DE', name: 'Muenchener Rueckversicherungs AG', exchange: 'XETRA', country: 'DE' },
  { symbol: 'NDA-FI.HE', name: 'Nordea Bank Abp', exchange: 'HELSINKI', country: 'FI' },
  { symbol: 'NDA.DE', name: 'Aurubis AG', exchange: 'XETRA', country: 'DE' },
  { symbol: 'NEM.DE', name: 'Nemetschek SE', exchange: 'XETRA', country: 'DE' },
  { symbol: 'NESTE.HE', name: 'Neste Oyj', exchange: 'HELSINKI', country: 'FI' },
  { symbol: 'NEXI.MI', name: 'Nexi SpA', exchange: 'BORSA_ITALIANA', country: 'IT' },
  { symbol: 'NK.PA', name: 'Imerys SA', exchange: 'EURONEXT_PAR', country: 'FR' },
  { symbol: 'NN.AS', name: 'NN Group NV', exchange: 'EURONEXT_AMS', country: 'NL' },
  { symbol: 'NOKIA.HE', name: 'Nokia Oyj', exchange: 'HELSINKI', country: 'FI' },
  { symbol: 'NOS.LS', name: 'NOS SGPS SA', exchange: 'EURONEXT_LIS', country: 'PT' },
  { symbol: 'NTGY.MC', name: 'Naturgy Energy Group SA', exchange: 'BME', country: 'ES' },
  { symbol: 'NVG.LS', name: 'Navigator Company SA', exchange: 'EURONEXT_LIS', country: 'PT' },
  { symbol: 'OCI.AS', name: 'OCI NV', exchange: 'EURONEXT_AMS', country: 'NL' },
  { symbol: 'OMV.VI', name: 'OMV AG', exchange: 'VIENNA', country: 'AT' },
  { symbol: 'OR.PA', name: 'L Oreal SA', exchange: 'EURONEXT_PAR', country: 'FR' },
  { symbol: 'ORNBV.HE', name: 'Orion Oyj', exchange: 'HELSINKI', country: 'FI' },
  { symbol: 'OUT1V.HE', name: 'Outokumpu Oyj', exchange: 'HELSINKI', country: 'FI' },
  { symbol: 'P911.DE', name: 'Dr. Ing. h.c. F. Porsche AG', exchange: 'XETRA', country: 'DE' },
  { symbol: 'PAH3.DE', name: 'Porsche Automobil Holding SE', exchange: 'XETRA', country: 'DE' },
  { symbol: 'PHIA.AS', name: 'Koninklijke Philips NV', exchange: 'EURONEXT_AMS', country: 'NL' },
  { symbol: 'PIRC.MI', name: 'Pirelli & C SpA', exchange: 'BORSA_ITALIANA', country: 'IT' },
  { symbol: 'POST.VI', name: 'Oesterreichische Post AG', exchange: 'VIENNA', country: 'AT' },
  { symbol: 'PROX.BR', name: 'Proximus PLC', exchange: 'EURONEXT_BRU', country: 'BE' },
  { symbol: 'PRX.AS', name: 'Prosus NV', exchange: 'EURONEXT_AMS', country: 'NL' },
  { symbol: 'PRY.MI', name: 'Prysmian SpA', exchange: 'BORSA_ITALIANA', country: 'IT' },
  { symbol: 'PST.MI', name: 'Poste Italiane SpA', exchange: 'BORSA_ITALIANA', country: 'IT' },
  { symbol: 'PUB.PA', name: 'Publicis Groupe SA', exchange: 'EURONEXT_PAR', country: 'FR' },
  { symbol: 'PUIG.MC', name: 'Puig Brands SA', exchange: 'BME', country: 'ES' },
  { symbol: 'PUM.DE', name: 'PUMA SE', exchange: 'XETRA', country: 'DE' },
  { symbol: 'QIA.DE', name: 'Qiagen NV', exchange: 'XETRA', country: 'DE' },
  { symbol: 'RAA.DE', name: 'Rational AG', exchange: 'XETRA', country: 'DE' },
  { symbol: 'RACE.MI', name: 'Ferrari NV', exchange: 'BORSA_ITALIANA', country: 'IT' },
  { symbol: 'RAND.AS', name: 'Randstad NV', exchange: 'EURONEXT_AMS', country: 'NL' },
  { symbol: 'RBI.VI', name: 'Raiffeisen Bank International AG', exchange: 'VIENNA', country: 'AT' },
  { symbol: 'RCO.PA', name: 'Remy Cointreau SA', exchange: 'EURONEXT_PAR', country: 'FR' },
  { symbol: 'REC.MI', name: 'Recordati Industria Chimica e Farmaceutica SpA', exchange: 'BORSA_ITALIANA', country: 'IT' },
  { symbol: 'RED.MC', name: 'Redeia Corporacion SA', exchange: 'BME', country: 'ES' },
  { symbol: 'REP.MC', name: 'Repsol SA', exchange: 'BME', country: 'ES' },
  { symbol: 'RHM.DE', name: 'Rheinmetall AG', exchange: 'XETRA', country: 'DE' },
  { symbol: 'RI.PA', name: 'Pernod Ricard SA', exchange: 'EURONEXT_PAR', country: 'FR' },
  { symbol: 'RMS.PA', name: 'Hermes International', exchange: 'EURONEXT_PAR', country: 'FR' },
  { symbol: 'RNO.PA', name: 'Renault SA', exchange: 'EURONEXT_PAR', country: 'FR' },
  { symbol: 'ROVI.MC', name: 'Laboratorios Farmaceuticos Rovi SA', exchange: 'BME', country: 'ES' },
  { symbol: 'RWE.DE', name: 'RWE AG', exchange: 'XETRA', country: 'DE' },
  { symbol: 'RXL.PA', name: 'Rexel SA', exchange: 'EURONEXT_PAR', country: 'FR' },
  { symbol: 'RYA.IR', name: 'Ryanair Holdings plc', exchange: 'EURONEXT_DUB', country: 'IE' },
  { symbol: 'SAB.MC', name: 'Banco de Sabadell SA', exchange: 'BME', country: 'ES' },
  { symbol: 'SAF.PA', name: 'Safran SA', exchange: 'EURONEXT_PAR', country: 'FR' },
  { symbol: 'SAMPO.HE', name: 'Sampo Oyj', exchange: 'HELSINKI', country: 'FI' },
  { symbol: 'SAN.MC', name: 'Banco Santander SA', exchange: 'BME', country: 'ES' },
  { symbol: 'SAN.PA', name: 'Sanofi SA', exchange: 'EURONEXT_PAR', country: 'FR' },
  { symbol: 'SAP.DE', name: 'SAP SE', exchange: 'XETRA', country: 'DE' },
  { symbol: 'SBMO.AS', name: 'SBM Offshore NV', exchange: 'EURONEXT_AMS', country: 'NL' },
  { symbol: 'SBO.VI', name: 'Schoeller-Bleckmann Oilfield Equipment AG', exchange: 'VIENNA', country: 'AT' },
  { symbol: 'SCYR.MC', name: 'Sacyr SA', exchange: 'BME', country: 'ES' },
  { symbol: 'SDF.DE', name: 'K+S AG', exchange: 'XETRA', country: 'DE' },
  { symbol: 'SEM.LS', name: 'Semapa SGPS SA', exchange: 'EURONEXT_LIS', country: 'PT' },
  { symbol: 'SESG.PA', name: 'SES SA', exchange: 'EURONEXT_PAR', country: 'FR' },
  { symbol: 'SGO.PA', name: 'Compagnie de Saint-Gobain SA', exchange: 'EURONEXT_PAR', country: 'FR' },
  { symbol: 'SHL.DE', name: 'Siemens Healthineers AG', exchange: 'XETRA', country: 'DE' },
  { symbol: 'SIE.DE', name: 'Siemens AG', exchange: 'XETRA', country: 'DE' },
  { symbol: 'SK.PA', name: 'SEB SA', exchange: 'EURONEXT_PAR', country: 'FR' },
  { symbol: 'SOF.BR', name: 'Sofina SA', exchange: 'EURONEXT_BRU', country: 'BE' },
  { symbol: 'SOLB.BR', name: 'Solvay SA', exchange: 'EURONEXT_BRU', country: 'BE' },
  { symbol: 'SON.LS', name: 'Sonae SGPS SA', exchange: 'EURONEXT_LIS', country: 'PT' },
  { symbol: 'SPM.MI', name: 'Saipem SpA', exchange: 'BORSA_ITALIANA', country: 'IT' },
  { symbol: 'SRG.MI', name: 'Snam SpA', exchange: 'BORSA_ITALIANA', country: 'IT' },
  { symbol: 'SRT3.DE', name: 'Sartorius AG', exchange: 'XETRA', country: 'DE' },
  { symbol: 'STERV.HE', name: 'Stora Enso Oyj', exchange: 'HELSINKI', country: 'FI' },
  { symbol: 'STLAM.MI', name: 'Stellantis NV', exchange: 'BORSA_ITALIANA', country: 'IT' },
  { symbol: 'STLAP.PA', name: 'Stellantis NV', exchange: 'EURONEXT_PAR', country: 'FR' },
  { symbol: 'STMPA.PA', name: 'STMicroelectronics NV', exchange: 'EURONEXT_PAR', country: 'FR' },
  { symbol: 'SU.PA', name: 'Schneider Electric SE', exchange: 'EURONEXT_PAR', country: 'FR' },
  { symbol: 'SW.PA', name: 'Sodexo SA', exchange: 'EURONEXT_PAR', country: 'FR' },
  { symbol: 'SY1.DE', name: 'Symrise AG', exchange: 'XETRA', country: 'DE' },
  { symbol: 'SZU.DE', name: 'Suedzucker AG', exchange: 'XETRA', country: 'DE' },
  { symbol: 'TEF.MC', name: 'Telefonica SA', exchange: 'BME', country: 'ES' },
  { symbol: 'TEG.DE', name: 'TAG Immobilien AG', exchange: 'XETRA', country: 'DE' },
  { symbol: 'TEN.MI', name: 'Tenaris SA', exchange: 'BORSA_ITALIANA', country: 'IT' },
  { symbol: 'TEP.PA', name: 'Teleperformance SE', exchange: 'EURONEXT_PAR', country: 'FR' },
  { symbol: 'TIETO.HE', name: 'TietoEVRY Oyj', exchange: 'HELSINKI', country: 'FI' },
  { symbol: 'TIT.MI', name: 'Telecom Italia SpA', exchange: 'BORSA_ITALIANA', country: 'IT' },
  { symbol: 'TKA.DE', name: 'thyssenkrupp AG', exchange: 'XETRA', country: 'DE' },
  { symbol: 'TKA.VI', name: 'Telekom Austria AG', exchange: 'VIENNA', country: 'AT' },
  { symbol: 'TLX.DE', name: 'Talanx AG', exchange: 'XETRA', country: 'DE' },
  { symbol: 'TRN.MI', name: 'Terna SpA', exchange: 'BORSA_ITALIANA', country: 'IT' },
  { symbol: 'TTE.PA', name: 'TotalEnergies SE', exchange: 'EURONEXT_PAR', country: 'FR' },
  { symbol: 'TUI1.DE', name: 'TUI AG', exchange: 'XETRA', country: 'DE' },
  { symbol: 'TWEKA.AS', name: 'TKH Group NV', exchange: 'EURONEXT_AMS', country: 'NL' },
  { symbol: 'TYRES.HE', name: 'Nokian Renkaat Oyj', exchange: 'HELSINKI', country: 'FI' },
  { symbol: 'UCB.BR', name: 'UCB SA', exchange: 'EURONEXT_BRU', country: 'BE' },
  { symbol: 'UCG.MI', name: 'UniCredit SpA', exchange: 'BORSA_ITALIANA', country: 'IT' },
  { symbol: 'UMI.BR', name: 'Umicore SA', exchange: 'EURONEXT_BRU', country: 'BE' },
  { symbol: 'UNI.MC', name: 'Unicaja Banco SA', exchange: 'BME', country: 'ES' },
  { symbol: 'UNI.MI', name: 'Unipol Gruppo SpA', exchange: 'BORSA_ITALIANA', country: 'IT' },
  { symbol: 'UPM.HE', name: 'UPM-Kymmene Oyj', exchange: 'HELSINKI', country: 'FI' },
  { symbol: 'UPR.IR', name: 'Uniphar plc', exchange: 'EURONEXT_DUB', country: 'IE' },
  { symbol: 'UQA.VI', name: 'UNIQA Insurance Group AG', exchange: 'VIENNA', country: 'AT' },
  { symbol: 'URW.PA', name: 'Unibail-Rodamco-Westfield SE', exchange: 'EURONEXT_PAR', country: 'FR' },
  { symbol: 'VALMT.HE', name: 'Valmet Oyj', exchange: 'HELSINKI', country: 'FI' },
  { symbol: 'VER.VI', name: 'Verbund AG', exchange: 'VIENNA', country: 'AT' },
  { symbol: 'VIE.PA', name: 'Veolia Environnement SA', exchange: 'EURONEXT_PAR', country: 'FR' },
  { symbol: 'VIV.PA', name: 'Vivendi SE', exchange: 'EURONEXT_PAR', country: 'FR' },
  { symbol: 'VNA.DE', name: 'Vonovia SE', exchange: 'XETRA', country: 'DE' },
  { symbol: 'VOE.VI', name: 'voestalpine AG', exchange: 'VIENNA', country: 'AT' },
  { symbol: 'VOW3.DE', name: 'Volkswagen AG', exchange: 'XETRA', country: 'DE' },
  { symbol: 'VPK.AS', name: 'Koninklijke Vopak NV', exchange: 'EURONEXT_AMS', country: 'NL' },
  { symbol: 'WAF.DE', name: 'Siltronic AG', exchange: 'XETRA', country: 'DE' },
  { symbol: 'WCH.DE', name: 'Wacker Chemie AG', exchange: 'XETRA', country: 'DE' },
  { symbol: 'WDP.BR', name: 'Warehouses De Pauw NV', exchange: 'EURONEXT_BRU', country: 'BE' },
  { symbol: 'WHA.AS', name: 'Wereldhave NV', exchange: 'EURONEXT_AMS', country: 'NL' },
  { symbol: 'WIE.VI', name: 'Wienerberger AG', exchange: 'VIENNA', country: 'AT' },
  { symbol: 'WKL.AS', name: 'Wolters Kluwer NV', exchange: 'EURONEXT_AMS', country: 'NL' },
  { symbol: 'WLN.PA', name: 'Worldline SA', exchange: 'EURONEXT_PAR', country: 'FR' },
  { symbol: 'WRT1V.HE', name: 'Wartsila Oyj Abp', exchange: 'HELSINKI', country: 'FI' },
  { symbol: 'ZAL.DE', name: 'Zalando SE', exchange: 'XETRA', country: 'DE' },
];

/** Load the curated eurozone universe (all EUR-denominated). */
export function loadEuUniverse(): EuUniverseCandidate[] {
  return EU_EUROZONE_UNIVERSE;
}
